#version 460
#extension GL_ARB_separate_shader_objects : enable

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set=1, binding = 0, r32f) 	uniform image2D depthBuffer;
layout(set=1, binding = 1, r16f) 	uniform image2D maxPyramid;

void main(){

	ivec2 uv = ivec2(gl_GlobalInvocationID.xy);
    
	float depth = imageLoad(depthBuffer, uv).r;
    
	imageStore(maxPyramid, uv, vec4(depth, vec3(0.f)));
}