#version 460
#extension GL_ARB_separate_shader_objects : enable

layout(constant_id = 0) const uint constNBins = 64;
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set=1, binding = 1, std430) buffer histogramBuffer{
    uint histogram[constNBins];
};

void main(){
    if(gl_GlobalInvocationID.x >= constNBins){
        return;
    }
    histogram[gl_GlobalInvocationID.x] = 0;
}